[colors]
bg          = "#121214"
bg_sidebar  = "#112028"
bg_input    = "#111a20"
bg_hover    = "#3b1100"
bg_active   = "#122c38"
text        = "#5ba4db"
text_dim    = "#2a6d8d"
text_server = "#c4756a"
border      = "#1a4458"
accent      = "#8c402c"
timestamp   = "#286886"
nick_self   = "#db8b84"
action      = "#c4756a"

[sidebar]
unread  = "#8c402c"
mention = "#9c4f3d"

[highlights]
mention    = "#9c4f3d"
mention_bg = "rgba(156,79,61,0.08)"
