[colors]
bg          = "#1e1d17"
bg_sidebar  = "#302d1e"
bg_input    = "#28261a"
bg_hover    = "#142e48"
bg_active   = "#3e3a25"
text        = "#c9c390"
text_dim    = "#857d50"
text_server = "#9bafd3"
border      = "#585335"
accent      = "#5479a6"
timestamp   = "#817a4e"
nick_self   = "#b8c4e4"
action      = "#9bafd3"

[sidebar]
unread  = "#5479a6"
mention = "#6889b3"

[highlights]
mention    = "#6889b3"
mention_bg = "rgba(104,137,179,0.08)"
