// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNick(arg1) {
  return window['go']['main']['App']['GetNick'](arg1);
}

export function GetNickList(arg1, arg2) {
  return window['go']['main']['App']['GetNickList'](arg1, arg2);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function PartChannel(arg1, arg2) {
  return window['go']['main']['App']['PartChannel'](arg1, arg2);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}
