// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetNick(arg1:string):Promise<string>;

export function GetServers():Promise<Array<config.Server>>;

export function PartChannel(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;
