// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppQuit() {
  return window['go']['main']['App']['AppQuit']();
}

export function BrowserOpen(arg1) {
  return window['go']['main']['App']['BrowserOpen'](arg1);
}

export function ConnectServer(arg1) {
  return window['go']['main']['App']['ConnectServer'](arg1);
}

export function DCCAccept(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DCCAccept'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DCCSend(arg1, arg2, arg3) {
  return window['go']['main']['App']['DCCSend'](arg1, arg2, arg3);
}

export function DisconnectServer(arg1) {
  return window['go']['main']['App']['DisconnectServer'](arg1);
}

export function FetchURLPreview(arg1) {
  return window['go']['main']['App']['FetchURLPreview'](arg1);
}

export function GetAppIcon() {
  return window['go']['main']['App']['GetAppIcon']();
}

export function GetNick(arg1) {
  return window['go']['main']['App']['GetNick'](arg1);
}

export function GetNickList(arg1, arg2) {
  return window['go']['main']['App']['GetNickList'](arg1, arg2);
}

export function GetScrollback() {
  return window['go']['main']['App']['GetScrollback']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSysInfo() {
  return window['go']['main']['App']['GetSysInfo']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetThemeByName(arg1) {
  return window['go']['main']['App']['GetThemeByName'](arg1);
}

export function GetThemeNames() {
  return window['go']['main']['App']['GetThemeNames']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function JoinChannel(arg1, arg2) {
  return window['go']['main']['App']['JoinChannel'](arg1, arg2);
}

export function ListChannels(arg1) {
  return window['go']['main']['App']['ListChannels'](arg1);
}

export function MaybeShowKeyboard() {
  return window['go']['main']['App']['MaybeShowKeyboard']();
}

export function NeedsNickSetup() {
  return window['go']['main']['App']['NeedsNickSetup']();
}

export function OpenConfig() {
  return window['go']['main']['App']['OpenConfig']();
}

export function PartChannel(arg1, arg2) {
  return window['go']['main']['App']['PartChannel'](arg1, arg2);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SendAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendAction'](arg1, arg2, arg3);
}

export function SendCTCP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendCTCP'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendNick(arg1, arg2) {
  return window['go']['main']['App']['SendNick'](arg1, arg2);
}

export function SendRaw(arg1, arg2) {
  return window['go']['main']['App']['SendRaw'](arg1, arg2);
}

export function SendTyping(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendTyping'](arg1, arg2, arg3);
}

export function SendWhois(arg1, arg2) {
  return window['go']['main']['App']['SendWhois'](arg1, arg2);
}

export function SetNick(arg1) {
  return window['go']['main']['App']['SetNick'](arg1);
}
