// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {preview} from '../models';
import {config} from '../models';
import {theme} from '../models';
import {main} from '../models';

export function AppQuit():Promise<void>;

export function BrowserOpen(arg1:string):Promise<void>;

export function ConnectServer(arg1:string):Promise<void>;

export function DisconnectServer(arg1:string):Promise<void>;

export function FetchURLPreview(arg1:string):Promise<preview.Result>;

export function GetAppIcon():Promise<string>;

export function GetNick(arg1:string):Promise<string>;

export function GetNickList(arg1:string,arg2:string):Promise<Array<string>>;

export function GetScrollback():Promise<number>;

export function GetServers():Promise<Array<config.Server>>;

export function GetSysInfo():Promise<string>;

export function GetTheme():Promise<theme.Colors>;

export function GetThemeByName(arg1:string):Promise<theme.Colors>;

export function GetThemeNames():Promise<Array<string>>;

export function JoinChannel(arg1:string,arg2:string):Promise<void>;

export function ListChannels(arg1:string):Promise<void>;

export function NeedsNickSetup():Promise<boolean>;

export function OpenConfig():Promise<void>;

export function PartChannel(arg1:string,arg2:string):Promise<void>;

export function ReadClipboard():Promise<string>;

export function ReloadConfig():Promise<main.UIConfig>;

export function RestartApp():Promise<void>;

export function SaveTheme(arg1:string):Promise<void>;

export function SendAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendCTCP(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendNick(arg1:string,arg2:string):Promise<void>;

export function SendRaw(arg1:string,arg2:string):Promise<void>;

export function SendTyping(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendWhois(arg1:string,arg2:string):Promise<void>;

export function SetNick(arg1:string):Promise<boolean>;
